// Options for the framework's particle library (packs/behemoth/RP/particles/*.particle.json,
// generated by tools/particles.py; list in docs/particles.md) → Molang
// variables passed when the particle is spawned. Every particle-drawing
// mechanic accepts them:
//   color  "#RRGGBB" or "#RRGGBBAA"  → variable.color_r/_g/_b/_a (0-1)
//   color2 "#RRGGBB[AA]"             → variable.color2_r/... (end colour, bhm:dust_transition)
// (colours are separate floats: the particles default every variable with `??`,
// which does not work for members of an unset RGBA struct).
//   size   blocks (half-size; radius for bhm:ring / bhm:telegraph) → variable.size
//   lifetime ticks                   → variable.lifetime (seconds)
//   speed  blocks/s (bhm:spark), deg/s (bhm:swirl)                  → variable.speed
//   amount particles per spawn       → variable.count
//   rise   blocks/s upward (bhm:swirl, bhm:smoke)                   → variable.rise
//   width  swirl radius, blocks      → variable.radius
// `vars` (raw { "variable.x": number }) is merged in.
// Vanilla particles ignore these variables.

const HEX = /^#?([0-9a-fA-F]{6})([0-9a-fA-F]{2})?$/;
const NUMBERS = { size: "variable.size", speed: "variable.speed", amount: "variable.count", rise: "variable.rise", width: "variable.radius" };

/**
 * @param {string} hex
 * @returns {{ red: number, green: number, blue: number, alpha: number } | undefined}
 */
export function parseColor(hex) {
  const m = HEX.exec(String(hex));
  if (!m) return undefined;
  const n = parseInt(m[1], 16);
  return { red: ((n >> 16) & 255) / 255, green: ((n >> 8) & 255) / 255, blue: (n & 255) / 255, alpha: m[2] ? parseInt(m[2], 16) / 255 : 1 };
}

/**
 * A colour as the four float variables the particles read.
 * @param {string} name "color" | "color2" @param {{ red: number, green: number, blue: number, alpha: number }} c
 * @returns {Record<string, number>}
 */
export function colorVars(name, c) {
  return { [`variable.${name}_r`]: c.red, [`variable.${name}_g`]: c.green, [`variable.${name}_b`]: c.blue, [`variable.${name}_a`]: c.alpha };
}

/** Validation errors for the particle options. @param {Record<string, any>} o */
export function particleOptionErrors(o) {
  const errors = [];
  for (const k of ["color", "color2"]) {
    if (o[k] !== undefined && !parseColor(o[k])) errors.push(`\`${k}\` must be #RRGGBB or #RRGGBBAA`);
  }
  for (const k of [...Object.keys(NUMBERS), "lifetime"]) {
    if (o[k] !== undefined && (typeof o[k] !== "number" || o[k] <= 0)) errors.push(`\`${k}\` must be a number > 0`);
  }
  return errors;
}

/**
 * Molang variables for a spawn, or undefined when there are none.
 * @param {Record<string, any>} o
 * @returns {Record<string, number> | undefined}
 */
export function particleVars(o) {
  /** @type {Record<string, number>} */
  const v = { ...(o.vars ?? {}) };
  const c1 = o.color !== undefined ? parseColor(o.color) : undefined;
  const c2 = o.color2 !== undefined ? parseColor(o.color2) : undefined;
  if (c1) Object.assign(v, colorVars("color", c1));
  if (c2) Object.assign(v, colorVars("color2", c2));
  for (const [k, name] of Object.entries(NUMBERS)) if (typeof o[k] === "number") v[name] = o[k];
  if (typeof o.lifetime === "number") v["variable.lifetime"] = o.lifetime / 20;
  return Object.keys(v).length ? v : undefined;
}
